replicaCount: 1

global:
  imagePullSecrets:
    - docker-secret
  security:
    allowInsecureImages: true
   
  librechat:
    existingSecretName: "librechat-credentials-env"

librechat:
  configEnv:
    LDAP_URL: "ldaps://sebadc01.seba.local:636"
    LDAP_BIND_DN: "CN=Read,OU=OU-User,OU=OU-IT,OU=OU-SEBA,DC=SEBA,DC=local"
    LDAP_BIND_CREDENTIALS: "${LDAP_BIND_PASSWORD}"
    LDAP_USER_SEARCH_BASE: "DC=SEBA,DC=local"
    #LDAP_SEARCH_FILTER: "(sAMAccountName={{username}})"
    LDAP_SEARCH_FILTER: "(&(sAMAccountName={{username}})(memberOf=CN=SG-AI-Chat,OU=OU-Security Group,OU=OU-IT,OU=OU-SEBA,DC=SEBA,DC=local))"
    LDAP_LOGIN_USES_USERNAME: "true"
    LDAP_CA_CERT_PATH: "/etc/librechat/certs/ca.crt"
    LDAP_TLS_REJECT_UNAUTHORIZED: "true"
    LDAP_ID: "sAMAccountName"
    LDAP_USERNAME: "sAMAccountName"
    LDAP_EMAIL: "mail"
    LDAP_FULL_NAME: "displayName"
   
  existingSecretName: "librechat-credentials-env"

  configYamlContent: |
    version: 1.3.0
    
    cache: true
    
    endpoints:
      custom:
        - name: "OpenRouter"
          apiKey: "${OPENROUTER_KEY}"
          baseURL: "https://openrouter.ai/api/v1" 
          models:
            default: 
              - "openai/gpt-oss-20b:free"
              - "moonshotai/kimi-k2:free"
              - "openai/gpt-5"
              - "anthropic/claude-sonnet-4.5"
              - "deepseek/deepseek-r1"
              - "google/gemini-2.5-flash"
              - "x-ai/grok-4"
              - "qwen/qwen-max"
              - "perplexity/sonar"
            #fetch: true
          titleConvo: true
          titleModel: "openai/gpt-3.5-turbo"
          summarize: false
          summaryModel: "openai/gpt-3.5-turbo"
          forcePrompt: false
          modelDisplayLabel: "OpenRouter"
          dropParams: ["user"]

  existingConfigYaml: ""

  imageVolume:
    enabled: true
    size: 20Gi            
    accessModes: ReadWriteOnce
    storageClassName: ceph-block

librechat-rag-api:
  enabled: false
  embeddingsProvider: openai

image:
  repository: danny-avila/librechat
  registry: docker.sebaoffice.ir
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: docker-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

lifecycle: {}

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 3080
  targetPort: 3080
  containerPort: 3080
  annotations: {}

ingress:
  enabled: true
  className: haproxy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    haproxy.org/request-set-header: |
      X-Forwarded-Proto https
    haproxy.org/proxy-body-size: 64m
  hosts:
    - host: chat.sebaoffice.ir
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: chat-sebaoffice-tls
      hosts:
        - chat.sebaoffice.ir

resources:
  limits:
    cpu: "1"
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

livenessProbe:
  httpGet:
    path: /health
    port: 3080
readinessProbe:
  httpGet:
    path: /health
    port: 3080

volumes:
  - name: ldap-ca-cert
    secret:
      secretName: ldap-ca-cert

volumeMounts:
  - name: ldap-ca-cert
    mountPath: /etc/librechat/certs
    readOnly: true
nodeSelector: {}
tolerations: []
affinity: {}
hostAliases: []
dnsPolicy: "" 
dnsConfig: {}

updateStrategy:
  type: RollingUpdate

mongodb:
  enabled: true
  auth:
    enabled: false
  databases:
   - LibreChat
  image:
    registry: docker.sebaoffice.ir
    repository: bitnami/mongodb
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 16Gi
    storageClass: ceph-block

meilisearch:
  enabled: true
  persistence:
    enabled: true
    storageClass: ceph-block
    size: 10Gi
  image:
    registry: docker.sebaoffice.ir
    repository: getmeili/meilisearch
    tag: "v1.7.3"
    pullPolicy: IfNotPresent
  auth:
    existingMasterKeySecret: "librechat-credentials-env"